"""Startup-latency test for omca-mcp.py.

Methodology
-----------
1. Spawn ``omca-mcp.py`` as a subprocess using the installed plugin path and
   the ``UV_PROJECT_ENVIRONMENT`` venv (stdio transport -- FastMCP default).
2. Record ``t0 = time.monotonic()`` immediately before ``Popen``.
3. Write a minimal valid JSON-RPC ``initialize`` request to the process stdin.
4. Record ``t1 = time.monotonic()`` after reading the first reply line on
   stdout (blocking readline).
5. Assert ``t1 - t0 < 0.5`` (500 ms).

Threshold rationale
-------------------
Empirical warm-cache measurements on the development machine consistently land
in the 260-290 ms range (uv venv already resolved, .pyc bytecode present).
500 ms gives ~2x headroom for CI variance while still catching regressions
like accidentally importing heavy libraries at module level or running a
blocking call before ``mcp.run()``.

Warm-cache definition
---------------------
"Warm" means EITHER (a) the ``UV_PROJECT_ENVIRONMENT`` venv's Python binary
exists on disk (uv will not need to create/resolve the virtual environment), OR
(b) the newest ``.pyc`` file under the plugin servers ``tools/`` directory is
newer than 60 seconds (bytecode freshly generated by a recent import).

Condition (a) is the primary signal: a persistent venv means ``uv run``
skips dependency resolution entirely and goes straight to spawning Python,
which is the dominant factor keeping warm-cache latency under 300 ms.
Condition (b) catches the edge-case where the venv exists but bytecode was
recently regenerated (e.g., after a plugin upgrade) and may not yet be
committed to the OS page cache.

If neither condition is met the test calls ``pytest.skip()`` with a clear
message -- it does NOT silently pass, and it does NOT attempt to warm the
cache itself (that would hide real cold-start regressions).

Transport
---------
``mcp.run()`` in omca-mcp.py is called with no arguments, so FastMCP uses its
default stdio transport (confirmed by reading the source: see
``servers/omca-mcp.py`` line with ``mcp.run()``).
"""

import json
import os
import subprocess
import time
from pathlib import Path

import pytest

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_PLUGIN_ROOT = Path("/home/utsav/.claude/plugins/cache/omca/oh-my-claudeagent/2.0.0")
_PLUGIN_DATA = Path("/home/utsav/.claude/plugins/data/oh-my-claudeagent-omca")
_SERVERS_DIR = _PLUGIN_ROOT / "servers"
_MCP_SCRIPT = _SERVERS_DIR / "omca-mcp.py"

# Latency threshold (seconds) -- 500 ms warm-cache ceiling.
_THRESHOLD_S = 0.5

# Cache-staleness limit (seconds): secondary warm signal -- skip if newest
# tools/*.pyc is older than this AND the venv python binary is absent.
_WARM_CACHE_WINDOW_S = 60

# The venv Python binary; if it exists, uv skips venv creation (primary warm signal).
_VENV_PYTHON = _PLUGIN_DATA / ".venv" / "bin" / "python"

_INIT_MSG = (
    json.dumps(
        {
            "jsonrpc": "2.0",
            "id": 1,
            "method": "initialize",
            "params": {
                "protocolVersion": "2024-11-05",
                "capabilities": {},
                "clientInfo": {"name": "latency-test", "version": "0"},
            },
        }
    )
    + "\n"
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _newest_pyc_age_s() -> float:
    """Return seconds since the newest .pyc under the plugin servers/tools dir was modified.

    Scans only the ``tools/`` source directory, NOT the venv, so we're
    measuring bytecode freshness for the actual server code.
    Returns ``inf`` if no .pyc files exist.
    """
    newest_mtime: float = 0.0
    tools_dir = _SERVERS_DIR / "tools"
    for pyc in tools_dir.rglob("*.pyc"):
        try:
            mt = pyc.stat().st_mtime
            if mt > newest_mtime:
                newest_mtime = mt
        except OSError:
            pass
    if newest_mtime == 0.0:
        return float("inf")
    return time.time() - newest_mtime


def _is_warm_cache() -> tuple[bool, str]:
    """Check warm-cache conditions.  Returns (is_warm, reason_str)."""
    # Primary: venv python binary exists -> uv skips venv resolution.
    if _VENV_PYTHON.exists():
        return True, f"venv python present at {_VENV_PYTHON}"
    # Secondary: source bytecode freshly generated.
    age = _newest_pyc_age_s()
    if age <= _WARM_CACHE_WINDOW_S:
        return True, f"tools pyc age {age:.1f}s <= {_WARM_CACHE_WINDOW_S}s"
    return False, (
        f"venv python absent and tools pyc age {age:.0f}s > {_WARM_CACHE_WINDOW_S}s"
    )


def _spawn_server() -> subprocess.Popen:
    """Spawn omca-mcp.py via uv run with the plugin venv."""
    env = dict(os.environ)
    env["UV_PROJECT_ENVIRONMENT"] = str(_PLUGIN_DATA / ".venv")
    return subprocess.Popen(
        [
            "uv",
            "run",
            "--project",
            str(_SERVERS_DIR),
            "python",
            str(_MCP_SCRIPT),
        ],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env=env,
    )


def _teardown(proc: subprocess.Popen) -> None:
    """Kill the server subprocess and reap it."""
    try:
        proc.kill()
        proc.communicate(timeout=3)
    except Exception:
        pass


# ---------------------------------------------------------------------------
# Fixture
# ---------------------------------------------------------------------------


@pytest.fixture
def server_proc():
    """Spawn the MCP server and tear it down after the test."""
    proc = _spawn_server()
    yield proc
    _teardown(proc)


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


def test_initialize_latency_warm_cache(server_proc):
    """Measure time from spawn to first initialize reply; assert < 500 ms.

    Skips when bytecode cache is cold (newest .pyc older than 60 s) to avoid
    a false pass on a machine that just checked out the repo.
    """
    warm, warm_reason = _is_warm_cache()
    if not warm:
        pytest.skip(
            f"Cold cache: {warm_reason}. "
            "Run pytest twice consecutively or after a recent import to warm the cache."
        )

    proc = server_proc

    # t0: spawn already happened inside the fixture; we record right before sending.
    # Re-spawn to get a clean t0 that includes process creation cost.
    _teardown(proc)

    env = dict(os.environ)
    env["UV_PROJECT_ENVIRONMENT"] = str(_PLUGIN_DATA / ".venv")

    t0 = time.monotonic()
    fresh = subprocess.Popen(
        [
            "uv",
            "run",
            "--project",
            str(_SERVERS_DIR),
            "python",
            str(_MCP_SCRIPT),
        ],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env=env,
    )
    try:
        fresh.stdin.write(_INIT_MSG.encode())
        fresh.stdin.flush()
        reply_line = fresh.stdout.readline()
        t1 = time.monotonic()
    finally:
        _teardown(fresh)

    elapsed_ms = (t1 - t0) * 1000
    assert reply_line, "No reply received from initialize request"

    reply = json.loads(reply_line)
    assert reply.get("id") == 1, f"Unexpected reply id: {reply}"
    assert "result" in reply, f"initialize reply missing 'result': {reply}"

    assert (t1 - t0) < _THRESHOLD_S, (
        f"Startup latency {elapsed_ms:.1f} ms exceeded {_THRESHOLD_S * 1000:.0f} ms threshold "
        f"(warm cache: {warm_reason})"
    )
